# Generated by Django 4.0.3 on 2022-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental_id',
            field=models.IntegerField(),
        ),
    ]
